spring:
  application:
    name: horizondesk

  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.horizondesk.api: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false